### ISSUE TITLE
Test on Predeployでの条件変更とRelease Drafterの微修正

### ISSUE THREAD

**Issue by Shirataki2** [Shirataki2/WebBash#46]
`.github/release-drafter.yml`
```yml
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 新機能"
    labels:
      - "Feature"
  - title: "🐛 バグ修正"
    labels:
      - "Bug"
  - title: "🧰 メンテナンス"
    labels:
      - "chore" <- 大文字にする
  - title: "🤖 自動化"
    labels:
      - "Automation"
...
```

### Test on Predeploy

コミットメッセージに[No CI]があれば実行しない
